language: dart

dart:
  - stable

os:
  - osx
  - windows
  - linux

before_install:
  - pub get

matrix:
  include:
    - os: osx
      env: FILENAME=piano_server-osx
    - os: windows
      env: FILENAME=piano_server-windows.exe
    - os: linux
      env: FILENAME=piano_server-linux

branches:
  only:
    - master

before_deploy:
  - mkdir release
  - dart2native lib/server.dart -o release/$FILENAME

deploy:
  provider: releases
  api_key:
    secure: tfEKWTETsaAqVtK7W+2KFA5D3WxfwcPzvNfzdZweI2aP6oqHHyZl99OsYAw7I+T3XRDJrqcUYpa3ffrq5kIsgnnPTW7Y3ZMTR4/7GUW0Htf+nLvR5UZaXl3DTrHr7ZOPJM6Dfz4FCazJ+wPm61GIzxtlm0oVwudnVQSho6aUSW4vJkNLB/2eizHVBJ3r2UsDj/csqPeYRnNhWOoa2OKxZEZz31nU/ZCNpPO0nXlIYOShfWFPvmMzi3fyIgwS60lTDD1yd6KI4yj9toCxgnzAju1S9XNnh+Rh1hHbFve/yZzk0JCiLsNSY4qbMlbIHUdW4UaLJFZkAPsTi/Osfu3HvsSWqmVfIFhQdqDzZhZz1O+xBTVpt+nKTAfXe7ojwBC50ndgVssSA6r4EGvSbM6G4Cpi0GNVW/AtmufgycZhiADf0gp7LP/N8tlRtf1Ug+OpCoIY72Gk5o+13bE6KLDScXETnRgPBYQShywneCx3JXD9x1mOVpYvDX07cqgkk416kfhDZYivyrcC0AoCdlKQm7eIfVgEJjvJ6bTHn22TbB11L4k740eaW8ovOZZkXAjeG4NGfSdQcNZFm4SYrlD4dB7xM5fSi/NAGwCraliEOV6FijlpO1Jotqs/7++cnveh08zOZzNXyTotScK89SU6fDXgws/SC6gZN1VMgtMcjJY=
  file:
    - release/piano_server-osx
    - release/piano_server-windows.exe
    - release/piano_server-linux
  skip_cleanup: true
  on:
    repo: kaboc/piano_server
    tags: true
