include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    unnecessary_null_comparison: warning
  exclude:
    - "lib/src/pb/*.dart"
